[package]
version = "1.0.1"
category = "Simulation"
title = "ZED calibration exporter"
description = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"
writeTarget.kit = true

[package.target]
platform = ["windows-x86_64", "linux-x86_64"]
kit = ["107.3"]

[dependencies]
"isaacsim.core.api" = {}
"isaacsim.gui.components" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "sl.sensor.camera.calibration_exporter"
